/**
 * 常量
 */
export class Const {
  /** 搜图页面 */
  static readonly soutu: string = 'soutu';
  /** 相册页面 */
  static readonly album: string = 'album';
  /** 仓库页面 */
  static readonly repo: string = 'repo';
  /** 设置页面 */
  static readonly setting: string = 'setting';
  /** 搜索页面 */
  static readonly search: string = 'search';
  /** 404 页面 */
  static readonly notFound: string = 'notFound';

  /** 搜索历史 */
  static readonly searchHistory: string = 'searchHistory';


  /** 站点初始化完成 */
  static readonly siteInit: string = 'siteInit';
}