/**
 * 常量
 */
export class Const {
  // ----------------------------------- 路由 -----------------------------------
  /** 搜图页面 */
  static readonly soutu: string = 'soutu';
  /** 相册页面 */
  static readonly album: string = 'album';
  /** 仓库页面 */
  static readonly repo: string = 'repo';
  /** 设置页面 */
  static readonly setting: string = 'setting';
  /** 搜索页面 */
  static readonly search: string = 'search';
  /** 图源管理页面 */
  static readonly imgSourceManage: string = 'imgSourceManage';
  /** 图床源管理页面 */
  static readonly bedSourceManage: string = 'bedSourceManage';
  /** 404 页面 */
  static readonly notFound: string = 'notFound';
  // ----------------------------------- 路由 -----------------------------------
  // ----------------------------------- 首选项键 -----------------------------------
  /** 搜索历史 */
  static readonly searchHistory: string = 'searchHistory';
  /** 历史数量 */
  static readonly historyCount = 100;
  /** 搜索页面选择的分组或源 */
  static readonly searchSelects: string = 'searchSelects';
  /** 主题模式 */
  static readonly themeMode: string = 'themeMode';
  // ----------------------------------- 首选项键 -----------------------------------
  // ----------------------------------- 事件 -----------------------------------
  /** 站点初始化完成 */
  static readonly siteInit: string = 'siteInit';
  // ----------------------------------- 事件 -----------------------------------
  // ----------------------------------- 参数 -----------------------------------
  /** 动画参数 */
  static readonly animate: AnimateParam = { duration: 200, curve: Curve.Ease };
  /** 动画参数 */
  static readonly animate3: AnimateParam = { duration: 300, curve: Curve.Ease };
  // ----------------------------------- 参数 -----------------------------------
  // ----------------------------------- 资源 -----------------------------------
  // ----------------------------------- 资源 -----------------------------------
}